#! /bin/sh
# /etc/init.d/lcd-ip

touch /var/lock/lcd-ip

case "$1" in
	start)
		echo "show IP on LCD"
		sudo python /home/pi/lcd/ip.py > /dev/null &
		;;
	kill)
		echo "killing LCD"
		kill -9 `ps aux|grep "python ip.py"|grep -vE "grep|sudo"|awk '{print $2}'`
		;;
	*)
		echo "Usage: /etc/init.d/lcd-ip {start|kill}"
		exit 1
		;;
esac
exit 0