#!/bin/sh
# /etc/init.d/lcd-ip
### BEGIN INIT INFO
# Provides:          lcd-ip
# Required-Start:    $local_fs $network led
# Required-Stop:     led
# Default-Start:     2 3 4 5 6
# Default-Stop:      0 1
# Short-Description: show IP address on LCD
### END INIT INFO

touch /var/lock/lcd-ip

case "$1" in
	start)
		echo "show IP on LCD"
		sudo python /home/pi/lcd/ip.py up
		;;
	stop)
		echo "show IP on LCD"
		sudo python /home/pi/lcd/ip.py down
		;;
	kill)
		echo "killing LCD"
		kill -9 `ps aux|grep "python ip.py"|grep -vE "grep|sudo"|awk '{print $2}'`
		;;
	*)
		echo "Usage: /etc/init.d/lcd-ip {start|kill}"
		exit 1
		;;
esac
exit 0